services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  orders.api:
    build:
      context: .
      dockerfile: Orders.Api/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RabbitMqConnectionOptions__HostName: ${RABBITMQ_HOST}
      RabbitMqConnectionOptions__Port: ${RABBITMQ_PORT}
      RabbitMqConnectionOptions__UserName: ${RABBITMQ_USER}
      RabbitMqConnectionOptions__Password: ${RABBITMQ_PASSWORD}
      ASPNETCORE_HTTP_PORTS: ${ASPNETCORE_HTTP_PORTS}
    ports:
      - "5096:8080"

  payments.worker:
    build:
      context: .
      dockerfile: Payments.Worker/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RabbitMqConnectionOptions__HostName: ${RABBITMQ_HOST}
      RabbitMqConnectionOptions__Port: ${RABBITMQ_PORT}
      RabbitMqConnectionOptions__UserName: ${RABBITMQ_USER}
      RabbitMqConnectionOptions__Password: ${RABBITMQ_PASSWORD}
      ASPNETCORE_HTTP_PORTS: ${ASPNETCORE_HTTP_PORTS}

  notifications.worker:
    build:
      context: .
      dockerfile: Notifications.Worker/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RabbitMqConnectionOptions__HostName: ${RABBITMQ_HOST}
      RabbitMqConnectionOptions__Port: ${RABBITMQ_PORT}
      RabbitMqConnectionOptions__UserName: ${RABBITMQ_USER}
      RabbitMqConnectionOptions__Password: ${RABBITMQ_PASSWORD}
      ASPNETCORE_HTTP_PORTS: ${ASPNETCORE_HTTP_PORTS}