services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  orders.api:
    build:
      context: .
      dockerfile: Orders.Api/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RabbitMqConnectionOptions__HostName: rabbitmq
      RabbitMqConnectionOptions__Port: 5672
      RabbitMqConnectionOptions__UserName: guest
      RabbitMqConnectionOptions__Password: guest
      ASPNETCORE_HTTP_PORTS: 8080
    ports:
      - "5096:8080"

  payments.worker:
    build:
      context: .
      dockerfile: Payments.Worker/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RabbitMqConnectionOptions__HostName: rabbitmq
      RabbitMqConnectionOptions__Port: 5672
      RabbitMqConnectionOptions__UserName: guest
      RabbitMqConnectionOptions__Password: guest
      ASPNETCORE_HTTP_PORTS: 8080

  notifications.worker:
    build:
      context: .
      dockerfile: Notifications.Worker/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RabbitMqConnectionOptions__HostName: rabbitmq
      RabbitMqConnectionOptions__Port: 5672
      RabbitMqConnectionOptions__UserName: guest
      RabbitMqConnectionOptions__Password: guest
      ASPNETCORE_HTTP_PORTS: 8080